esp32:
  board: nodemcu-32s
  framework:
    type: arduino

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - 116.203.244.102
      -  90.187.112.137
    # on_time:
    #   # trigger calibration once a day (if neccessary)
    #   - seconds: 0
    #     minutes: 0
    #     hours: 10
    #     then:
    #       - button.press: triggercalibration
    on_time_sync:
      then:
        - logger.log: "Time synchronized"

web_server:
  port: 80
  version: 2    

# Enable logging
logger:
  #No measurements, since it is too much for sun search
  level: INFO 

# Enable Home Assistant API
api:
  password: ""
  reboot_timeout: 0s

ota:
  password: ""

wifi:
  id: wifiid
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s # No reboot. Wifi is controled in status.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Webserver Fallback Hotspot"
    password: "PLsjAHFkVIKf"


mqtt:
  broker: !secret mqtt_broker
  port: 1883
  id: "mq"

captive_portal: