## Configuration of positions
                      
<<: !include constants.yaml
<<: !include base.yaml
<<: !include external.yaml

preferences:
  flash_write_interval: 8min

packages:
  webui: !include webui.yaml
  status: !include status.yaml
  motors: !include motors.yaml
  sensors: !include sensors.yaml
  calibration: !include calibration.yaml
  testfunctions: !include testfunctions.yaml
  suncalibration: !include suncalibration.yaml

esphome:
  name: heliostat
  includes: 
    - calculations.h

interval:
  # Update the mirror every 30s
  - interval: 30s
    then:
      script.execute: updatemirror

  # Search for the sun try every 3 minutes to see if sun is available
  # This has to be longer than the maximum sunsearch (500/4) = 125+x sec
  - interval: 3min
    then:
      - switch.turn_on: targetSun
 
  # find origin on startup
  # todo: find also a way to do complete calibration (maybe after some days?)
  - interval: 1000d #do only once
    then:
      - delay: 15s
#      - button.press: triggercalibration
      - button.press: triggerorigin