## Configuration of positions
                      
<<: !include constants.yaml
<<: !include base.yaml
<<: !include external.yaml

preferences:
  flash_write_interval: 8min

packages:
  webui: !include webui.yaml
  status: !include status.yaml
  motors: !include motors.yaml
  sensors: !include sensors.yaml
  calibration: !include calibration.yaml
  testfunctions: !include testfunctions.yaml
  suncalibration: !include suncalibration.yaml
  manualmode: !include manualmode.yaml

esphome:
  name: heliostat
  includes: 
    - helpers.h
    - status.h
    - motors.h
    - calibration.h
    - calculations.h

interval:
  # Update the mirror every 30s
  - interval: 30s
    then:
      script.execute: updatemirror

  # Search for the sun. 
  # Try every minute to see if sun is available
  # The routine will not move when it is not the right time
  # or too dark
  - interval: 1min
    then:
      - switch.turn_on: targetSun
 
  # find origin on startup
  # todo: find also a way to do complete calibration (maybe after some days?)
  - interval: 1000d #do only once
    then:
      - delay: 15s
#      - button.press: triggercalibration
      - button.press: triggerorigin