sun:
  latitude: ${Latitude}
  longitude: ${Longitude}

#experimental, currently not used:
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

ads1115:
  - address: 0x48


sensor:
  - platform: sun
    name: "Sun Elevation"
    id: "elevation"
    type: elevation
    update_interval: 15s

  - platform: sun
    name: "Sun Azimuth"
    id: "azimuth"
    type: azimuth
    update_interval: 15s

  - platform: ads1115
    update_interval: 30s
    multiplexer: 'A0_GND'
    gain: 4.096
    id: "sunlight1"
    name: "Sunlight"

  - platform: ads1115
    update_interval: 30s
    multiplexer: 'A1_GND'
    gain: 4.096
    name: "Sun_10"
